---
- name: Apply All configurations in Minikube and create Secret
  hosts: all
  #become: yes  # Optional, if sudo permissions are required
  tasks:
    - name: Apply All configurations
      command: kubectl apply -f . -R
      args:
        # chdir: ../
        chdir: ../deploy
      register: apply_result
    
    - name: Delete api-token secret if it exists
      command: kubectl delete -n monitoring-project secret api-token
      ignore_errors: yes
    
    - name: Delete slack-webhook secret if it exists
      command: kubectl delete -n monitoring-project secret slack-webhook
      ignore_errors: yes
    
    - name: Wait for deletion to complete
      wait_for:
        timeout: 2
    
    - name: Read API_TOKEN from .env file
      shell: |
        grep API_TOKEN ../src/.env | cut -d '=' -f2 | tr -d ' \t\r\n'
      args:
        executable: /bin/bash
      register: api_token_value
    
    - name: Read SLACK_WEBHOOK_URL from .env file
      shell: |
        grep SLACK_WEBHOOK_URL ../src/.env | cut -d '=' -f2 | tr -d ' \t\r\n'
      args:
        executable: /bin/bash
      register: slack_webhook_value

    - name: Create api-token secret
      command: kubectl create secret generic api-token --from-literal=token={{api_token_value.stdout}} -n monitoring-project
    
    - name: Create slack-webhook secret
      command: kubectl create secret generic slack-webhook --from-literal=token={{slack_webhook_value.stdout}} -n monitoring-project

    - name: Display kubectl apply output
      debug:
        var: apply_result.stdout_lines
